[build]
publish = "public"
command = "cd themes/hugo-future-imperfect-slim && git submodule update -f --init && cd ../.. && hugo --gc --minify --enableGitInfo"

[context.production.environment]
HUGO_VERSION = "0.80.0"
HUGO_ENV = "production"
HUGO_ENABLEGITINFO = "true"

[context.split1]
command = "hugo --gc --minify --enableGitInfo"

[context.split1.environment]
HUGO_VERSION = "0.80.0"
HUGO_ENV = "production"

[context.deploy-preview]
command = "hugo --gc --minify --enableGitInfo --buildFuture -b $DEPLOY_PRIME_URL"

[context.deploy-preview.environment]
HUGO_VERSION = "0.80.0"

[context.branch-deploy]
command = "hugo --gc --minify --enableGitInfo -b $DEPLOY_PRIME_URL"

[context.branch-deploy.environment]
HUGO_VERSION = "0.80.0"

[context.next.environment]
HUGO_ENABLEGITINFO = "true"

[[headers]]
  for = "/*"

  [headers.values]
   Strict-Transport-Security = "max-age=16070400; includeSubDomains; preload"
   X-Frame-Options = "DENY"

[[redirects]]
  from = "https://isd-atl-bsa.netlify.com/*"
  to = "https://www.indianspringsbsa.org/:splat"
  status = 301
  force = true #COMMENT: ensure that we always redirect
