---
backend:
  name: git-gateway
  branch: master # Branch to update (optional; defaults to master)
  squash_merges: true
publish_mode: editorial_workflow
media_folder: static/uploads
public_folder: /uploads
collections:
  - name: 'blog'
    label: 'Blog'
    folder: 'content/blog'
    create: true
    slug: '{{year}}-{{month}}-{{day}}-{{slug}}'
    editor:
      preview: true
    fields:
      - label: 'Title'
        name: 'title'
        widget: 'string'
      - label: 'Publish Date'
        name: 'date'
        widget: 'datetime'
      - label: 'Description'
        name: 'description'
        widget: 'string'
      - lable: 'Categories'
        name: 'categories'
        widget: 'list'
        default:
          - 'Announcement'
      - lable: 'Tags'
        name: 'tags'
        widget: 'list'
      - label: 'Type'
        name: 'type'
        widget: 'string'
        default: 'post'
      - label: 'Body'
        name: 'body'
        widget: 'markdown'
  - label: "Site Pages"
    name: "site_pages"
    files:
      - label: "About Page"
        name: "about"
        file: "content/about/_index.md"
        fields:
          - label: 'Title'
            name: 'title'
            widget: 'string'
            default: 'About Indian Springs District, BSA'
          - label: 'Body'
            name: 'body'
            widget: 'markdown'
  - label: "Commissioner Pages"
    name: "commissioner_pages"
    files:
      - label: "Commissioners Page"
        name: "commissioners"
        file: "content/commissioners/_index.md"
        fields:
          - label: 'Title'
            name: 'title'
            widget: 'string'
          - label: 'Description'
            name: 'description'
            widget: 'string'
          - label: 'Body'
            name: 'body'
            widget: 'markdown'
      - label: "Roundtable Page"
        name: "roundtable"
        file: "content/commissioners/roundtable/_index.md"
        fields:
          - label: 'Title'
            name: 'title'
            widget: 'string'
          - label: 'Description'
            name: 'description'
            widget: 'string'
          - label: 'Body'
            name: 'body'
            widget: 'markdown'
      - label: "Roundtable Documents"
        name: "roundtable-documents"
        file: "content/commissioners/roundtable/documents.md"
        fields:
          - label: 'Title'
            name: 'title'
            widget: 'string'
          - label: 'Description'
            name: 'description'
            widget: 'string'
          - label: 'Body'
            name: 'body'
            widget: 'markdown'
      - label: "Roundtable Links"
        name: "roundtable-links"
        file: "content/commissioners/roundtable/links.md"
        fields:
          - label: 'Title'
            name: 'title'
            widget: 'string'
          - label: 'Description'
            name: 'description'
            widget: 'string'
          - label: 'Body'
            name: 'body'
            widget: 'markdown'
      - label: "Unit Commissioners Page"
        name: "unit"
        file: "content/commissioners/unit/_index.md"
        fields:
          - label: 'Title'
            name: 'title'
            widget: 'string'
          - label: 'Description'
            name: 'description'
            widget: 'string'
          - label: 'Body'
            name: 'body'
            widget: 'markdown'
  - label: "Committee Pages"
    name: "committee_pages"
    files:
      - label: "Communication Page"
        name: "communication"
        file: "content/committee/vc-program/communications/_index.md"
        fields:
          - label: 'Title'
            name: 'title'
            widget: 'string'
          - label: 'Description'
            name: 'description'
            widget: 'string'
          - label: 'Body'
            name: 'body'
            widget: 'markdown'
      - label: "Webmasters Page"
        name: "webmaster"
        file: "content/committee/vc-program/communications/webmasters.md"
        fields:
          - label: 'Title'
            name: 'title'
            widget: 'string'
          - label: 'Description'
            name: 'description'
            widget: 'string'
          - label: 'Body'
            name: 'body'
            widget: 'markdown'
      - label: "Admin Guide"
        name: "admin_guide"
        file: "content/committee/vc-program/communications/admin-guide.md"
        fields:
          - label: 'Title'
            name: 'title'
            widget: 'string'
          - label: 'Description'
            name: 'description'
            widget: 'string'
          - label: 'Body'
            name: 'body'
            widget: 'markdown'
      - label: "Home Page"
        name: "home"
        file: "content/_index.md"
        fields:
          - label: 'Hero Image'
            name: 'hero_image'
            widget: 'string'
          - label: 'Hero Alt Text'
            name: 'hero_alt_text'
            widget: 'string'
          - label: 'Body'
            name: 'body'
            widget: 'markdown'
